### ISSUE TITLE
Details in the paper

### ISSUE THREAD

**Issue by tttao-uwu** [malldimi1/UnsupervisedLandmarks#3]
Hello, I have some questions to ask while reading your paper and code. Because I see that the landmarks are selected according to the threshold value in the code, I would like to ask, for the first stage of training, is the number of landmarks extracted from each instance image the same?

**Comment by dimitrismallis** [comment]
No, the number of landmarks extracted from each image would not be the same.

As you said, during correspondence recovery (stage 1) we discard the assignment of a landmark to a cluster (and the landmark) when its distance to the cluster centroid is much larger compared to the average distance to that centroid. As a result, different images would have a different number of detected points depending on how many good correspondences were found.

**Comment by tttao-uwu** [comment]
Thank you for your answer. I have another question. Since the number of landmarks extracted from each image is different in stage 1 , how to make the number of landmarks extracted from each image the same in stage 2 ?

**Comment by dimitrismallis** [comment]
Hi,

Extracted keypoints are clustered to a fixed number of clusters M in Stage 1. Even though, training images are pseudo-annotated with less than M keypoints (multiple points are missing), we can train our model in Stage 2 to detect one output channel per cluster. We simply calculate the loss, only for channels where the corresponding cluster has been detected for a particular image.

As a result, a fixed number of landmarks can be detected per image in the Stage 2, equal to the number of clusters learned by our method (reduced from M to K after the progressive cluster merging step, described in Sec 3.3 of the paper). Landmarks are simply detected as the channel coordinate with the highest probability response.

**Comment by tttao-uwu** [comment]
Hi,
if （just a hypothesis）the number of extracted landmarks is less than K （not M） ,so what should we do?

**Comment by dimitrismallis** [comment]
Hi, Apologies for the delay,

As mentioned, extracting a small number of keypoints (less than both M and K) is expected in Stage 1 and does not affect training in Stage 2. In Stage 2, we only train for the output channels where the corresponding cluster has been detected.

Hope this answers, If not, please elaborate with more details about this question.

**Comment by tttao-uwu** [comment]
Thank you very much for your answer and look forward to your follow-up work.

**Comment by dimitrismallis** [comment]
Thank you for your interest in our work, FYI an extension of our method is available [here](https://github.com/dimitrismallis/KeypointsToLandmarks).
